# yaml configuration file for running SPORES algorithm

config_name: "spores"
model_interface: pypsa
cost_slack: 0.2
alternatives: 5
spatially_explicit: True
intensification_coefficient: 0
diversified_technologies: ["wind", "solar", "gas", "battery"]
intensified_technologies: []
