# yaml configuration file for running SPORES algorithm

config_name: "spores"
model_interface: pypsa
cost_slack: 0.2
alternatives: 5
spatially_explicit: True
diversified_technologies: ["wind", "solar", "gas", "battery"]
intensified_technologies: ["wind", "solar"]
intensification_coefficient: [1, -1] # maximize wind, minimize solar
